Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 4
Rules claiming more threads will be scaled down.
Job stats:
job                 count    min threads    max threads
----------------  -------  -------------  -------------
varsel_pol_model        1              1              1
total                   1              1              1

Select jobs to execute...

[Tue Jan 11 11:28:21 2022]
rule varsel_pol_model:
    input: ../results/models/td_ref_pol_fit.rds, ../results/processed_data/pol_dat.rds
    log: ../results/logs/02_varsel_ref_pol_model.log
    jobid: 0
    resources: tmpdir=/var/folders/hl/dt523djx7_q7xjrthzjpdvc40000gn/T

[Tue Jan 11 11:28:21 2022]
Error in rule varsel_pol_model:
    jobid: 0
    log: ../results/logs/02_varsel_ref_pol_model.log (check log file(s) for error message)

RuleException:
WorkflowError in line 12 of /Users/corrado/_repositories/fake_news_wf/fake_news/workflow/rules/varsel_ref_pol_td.smk:
Failed to open source file /Users/corrado/_repositories/fake_news_wf/fake_news/workflow/rules/../scripts/analysis/02_varsel_ref_pol_model.R
FileNotFoundError: [Errno 2] No such file or directory: '/Users/corrado/_repositories/fake_news_wf/fake_news/workflow/rules/../scripts/analysis/02_varsel_ref_pol_model.R'
  File "/Users/corrado/_repositories/fake_news_wf/fake_news/workflow/rules/varsel_ref_pol_td.smk", line 12, in __rule_varsel_pol_model
  File "/opt/anaconda3/lib/python3.8/concurrent/futures/thread.py", line 57, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /Users/corrado/_repositories/fake_news_wf/fake_news/workflow/.snakemake/log/2022-01-11T112821.683475.snakemake.log
